// Michelin Guide overlay.
//
// We bundle a dataset of the world's 1/2/3-star restaurants (src/data/michelin.json,
// generated by scripts/build-michelin-data.mjs). On a restaurant detail page we
// look the place up and, when it matches, surface its star count, a link to its
// Michelin Guide page, and override the displayed cuisine + price.
//
// Matching is COORDINATE-PRIMARY. The dataset includes precise lat/lng for every
// restaurant, so we find Michelin records physically near the Google place and
// confirm with a tolerant name-similarity check. This is far more reliable than
// name matching alone: it tolerates name differences between Google and Michelin
// ("Restaurant Le X" vs "Le X", accents, articles, "by <chef>" suffixes) while
// still disambiguating multiple starred restaurants in the same building.

import { priceLevelToString } from './places';
import { haversineDistanceMi } from './distance';

export interface MichelinInfo {
  name: string;
  city: string;
  country: string;
  /** 1, 2, or 3 Michelin stars. */
  stars: 1 | 2 | 3;
  /** Price tier 1-4 (count of currency symbols in the source). */
  priceTier: number;
  /** Cuisine string, possibly comma-separated ("Modern Cuisine, Creative"). */
  cuisine: string;
  /** Michelin Guide page URL. */
  guideUrl: string;
  /** Awarded a Michelin Green Star (sustainability). */
  greenStar: boolean;
  /** Source coordinates (present for all current records). */
  lat: number;
  lng: number;
}

// Compact on-disk record shape (see scripts/build-michelin-data.mjs).
interface RawRecord {
  n: string;
  c: string;
  co: string;
  s: 1 | 2 | 3;
  pt: number;
  cu: string;
  u: string;
  la?: number;
  lng?: number;
  g?: boolean;
}

// ── Tuning constants ────────────────────────────────────────────────────────
// Google and Michelin coordinates for the same venue are usually within a few
// tens of metres, but can differ more for places inside hotels/malls or when
// one geocodes to a building entrance. We search a generous radius and lean on
// the name check to reject coincidental neighbours.
const NEAR_RADIUS_MI = 0.12;          // ~190 m: candidate search radius
const STRONG_COORD_MI = 0.03;         // ~48 m: "basically the same point"
const NAME_ACCEPT = 0.6;              // min token-overlap similarity to accept
const NAME_STRONG = 0.84;             // similarity that accepts on its own
// Grid cell size in degrees for the spatial index. 0.1deg ~ 11 km lat, so a
// candidate within NEAR_RADIUS_MI always lies in the cell or an immediate
// neighbour — we scan the 3x3 block around the query cell.
const CELL = 0.1;

// Lowercase, strip diacritics, drop punctuation, collapse whitespace.
export function normalize(s: string): string {
  return (s || '')
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '') // combining diacritical marks
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

// Generic tokens that shouldn't drive a name match on their own — they appear
// across huge numbers of restaurant names in several languages.
const STOPWORDS = new Set([
  'restaurant', 'restaurante', 'ristorante', 'le', 'la', 'les', 'l', 'el', 'il',
  'the', 'a', 'de', 'du', 'des', 'di', 'da', 'der', 'die', 'das', 'and', 'by',
  'cafe', 'bar', 'kitchen', 'cucina', 'osteria', 'trattoria', 'casa', 'chez',
]);

function tokenize(name: string): string[] {
  return normalize(name).split(' ').filter(Boolean);
}

function contentTokens(name: string): string[] {
  const toks = tokenize(name);
  const content = toks.filter((t) => t.length > 1 && !STOPWORDS.has(t));
  return content.length ? content : toks; // fall back if name is all stopwords
}

// Symmetric token-overlap similarity in [0,1]. Uses content tokens (stopwords
// removed) so "Le Bernardin" vs "Bernardin" or "Restaurant Tim Raue" vs
// "Tim Raue" score as a strong match. Falls back to substring containment so a
// fully-contained name (e.g. one is a prefix of the other) still scores high.
function nameSimilarity(a: string, b: string): number {
  const na = normalize(a);
  const nb = normalize(b);
  if (!na || !nb) return 0;
  if (na === nb) return 1;

  const ta = new Set(contentTokens(a));
  const tb = new Set(contentTokens(b));
  if (ta.size === 0 || tb.size === 0) return 0;

  let inter = 0;
  for (const t of ta) if (tb.has(t)) inter++;
  const overlap = inter / Math.min(ta.size, tb.size); // contained-name friendly

  // Substring bonus: one normalized name fully contains the other.
  const contains = na.includes(nb) || nb.includes(na) ? 0.85 : 0;

  return Math.max(overlap, contains);
}

type Grid = Map<string, MichelinInfo[]>;

interface MichelinIndex {
  grid: Grid;
  /** Records lacking coordinates, indexed by normalized name (rare/none now). */
  byName: Map<string, MichelinInfo[]>;
}

let indexPromise: Promise<MichelinIndex> | null = null;

function toInfo(r: RawRecord): MichelinInfo {
  return {
    name: r.n,
    city: r.c,
    country: r.co,
    stars: r.s,
    priceTier: r.pt,
    cuisine: r.cu,
    guideUrl: r.u,
    greenStar: !!r.g,
    lat: r.la ?? NaN,
    lng: r.lng ?? NaN,
  };
}

function cellKey(lat: number, lng: number): string {
  return `${Math.floor(lat / CELL)}:${Math.floor(lng / CELL)}`;
}

// Lazily load + index the dataset. The JSON is a dynamic import so it is
// code-split out of the main bundle and only fetched the first time a detail
// page performs a lookup.
function loadIndex(): Promise<MichelinIndex> {
  if (!indexPromise) {
    indexPromise = import('../data/michelin.json')
      .then((mod) => {
        const records = ((mod as { default?: RawRecord[] }).default
          || (mod as unknown as RawRecord[])) as RawRecord[];
        const grid: Grid = new Map();
        const byName: Map<string, MichelinInfo[]> = new Map();
        for (const r of records) {
          const info = toInfo(r);
          if (Number.isFinite(info.lat) && Number.isFinite(info.lng)) {
            const key = cellKey(info.lat, info.lng);
            const bucket = grid.get(key);
            if (bucket) bucket.push(info);
            else grid.set(key, [info]);
          } else {
            const key = normalize(info.name);
            if (!key) continue;
            const bucket = byName.get(key);
            if (bucket) bucket.push(info);
            else byName.set(key, [info]);
          }
        }
        return { grid, byName };
      })
      .catch((err) => {
        console.error('[Michelin] failed to load dataset', err);
        return { grid: new Map(), byName: new Map() } as MichelinIndex;
      });
  }
  return indexPromise;
}

// Collect candidate records within the 3x3 grid block around (lat,lng).
function candidatesNear(index: MichelinIndex, lat: number, lng: number): MichelinInfo[] {
  const baseLat = Math.floor(lat / CELL);
  const baseLng = Math.floor(lng / CELL);
  const out: MichelinInfo[] = [];
  for (let dLat = -1; dLat <= 1; dLat++) {
    for (let dLng = -1; dLng <= 1; dLng++) {
      const bucket = index.grid.get(`${baseLat + dLat}:${baseLng + dLng}`);
      if (bucket) out.push(...bucket);
    }
  }
  return out;
}

/**
 * Find the Michelin record for a Google place. Coordinate-primary:
 *
 *  1. Gather Michelin records within ~190 m of the place.
 *  2. Score each by distance + name similarity.
 *  3. Accept the best when it's either very close to the same point, or a
 *     near-coincident point with a plausible name, or a strong name match
 *     anywhere in range. This disambiguates multiple starred restaurants in
 *     one building (same coords → name decides) while tolerating name drift
 *     between Google and Michelin (same name → small coord delta is fine).
 *
 * Falls back to name-only matching if the place has no usable coordinates
 * (or, defensively, for any coordinate-less dataset rows).
 *
 * @param name    Google place display name.
 * @param lat     Google place latitude (NaN/undefined when unknown).
 * @param lng     Google place longitude.
 * @param address Best available address — used only for the name-only fallback.
 */
export async function findMichelinMatch(
  name: string,
  lat?: number,
  lng?: number,
  address?: string,
): Promise<MichelinInfo | null> {
  const index = await loadIndex();
  const hasCoord = Number.isFinite(lat) && Number.isFinite(lng);

  if (hasCoord) {
    const candidates = candidatesNear(index, lat as number, lng as number);
    let best: MichelinInfo | null = null;
    let bestScore = -Infinity;
    let bestDist = Infinity;
    for (const cand of candidates) {
      const dist = haversineDistanceMi(lat as number, lng as number, cand.lat, cand.lng);
      if (dist > NEAR_RADIUS_MI) continue;
      const sim = nameSimilarity(name, cand.name);
      // Acceptance: same physical point (name almost irrelevant — coords are
      // authoritative), OR a decent name match within the wider radius, OR a
      // very strong name match regardless of small coordinate disagreement.
      const accept =
        dist <= STRONG_COORD_MI ||
        sim >= NAME_ACCEPT ||
        (sim >= NAME_STRONG && dist <= NEAR_RADIUS_MI);
      if (!accept) continue;
      // Rank: prioritise name similarity, then proximity. (A 0–1 sim dominates;
      // the small distance term only breaks ties between similar names.)
      const score = sim * 2 + (1 - dist / NEAR_RADIUS_MI);
      if (score > bestScore || (score === bestScore && dist < bestDist)) {
        best = cand;
        bestScore = score;
        bestDist = dist;
      }
    }
    if (best) return best;
    // No coordinate match — fall through to name-only as a last resort. This
    // catches cases where Google's coordinate is off by more than the search
    // radius but the name is unambiguous.
  }

  // ── Name-only fallback ──────────────────────────────────────────────────
  const key = normalize(name);
  if (!key) return null;

  // Exact normalized-name hits live in two places: the rare coordinate-less
  // byName bucket, and (more usefully) a scan over the grid for an exact name.
  // We only accept a name-only match when the city/address agrees, to avoid
  // tagging a same-name restaurant in a different city.
  const normAddr = normalize(address || '');
  const cityMatches = (info: MichelinInfo): boolean => {
    if (!normAddr) return false;
    const c = normalize(info.city);
    if (!c) return false;
    if (normAddr.includes(c)) return true;
    const first = c.split(' ')[0];
    return first.length >= 4 && normAddr.includes(first);
  };

  const byNameHits = index.byName.get(key) || [];
  for (const cand of byNameHits) {
    if (!normAddr || cityMatches(cand)) return cand;
  }
  return null;
}

/** Render the Michelin price tier using the app's standard `$`-tier formatter. */
export function michelinPriceDisplay(info: MichelinInfo): string {
  return priceLevelToString(info.priceTier);
}
