import type { ReviewSnapshot } from './in-review';
export interface ReviewStory {
  id: string; kicker: string; title: string; detail: string; number?: string; suffix?: string;
  visual: 'cover' | 'orbit' | 'bars' | 'podium' | 'kitchen' | 'timeline' | 'taste' | 'community' | 'summary';
  rows?: { label: string; value: string }[]; pro?: boolean;
}
const plural = (n:number, one:string, many=one+'s') => `${n} ${n===1?one:many}`;
export function reviewStories(r: ReviewSnapshot): ReviewStory[] {
  const annual = r.period.kind === 'year';
  const time = r.period.kind;
  const activity = r.visits+r.meals+r.recipes;
  const pages: ReviewStory[] = [{ id:'cover', kicker:annual?'THE ANNUAL EDITION':'YOUR '+time.toUpperCase()+', REPLAYED', title:annual?'A year.\nAll your flavor.':time==='month'?'Good taste\nhas a rhythm.':'Small moments.\nGreat taste.', detail:r.period.label, visual:'cover', number:annual?r.period.label:undefined },
    { id:'moments', kicker:'LOOK WHAT YOU MADE OF IT', title:activity?'You made room\nfor good food.':'Your next favorites\nare taking shape.', detail:r.visits>r.previous.visits?`${plural(r.visits-r.previous.visits,'more logged visit')} than the previous ${time}.`: 'Every place saved and every meal logged is part of your story.', number:String(activity || r.saved), suffix:activity?'food moments':'places saved', visual:'orbit', rows:[{label:'Logged visits',value:String(r.visits)},{label:'Places rated',value:String(r.places)},{label:'Home meals',value:String(r.meals)},{label:'Recipes created',value:String(r.recipes)}] }];
  if (r.cuisines.length) pages.push({id:'flavors',kicker:'YOUR FLAVOR OF THE '+time.toUpperCase(),title:r.cuisines[0].name+'\nhad your heart.',detail:`${plural(r.cuisines.length,'cuisine')} across your rated places.${r.newCuisines.length?` ${plural(r.newCuisines.length,'new cuisine')} in your logged history.`:''}`,visual:'bars',rows:r.cuisines.slice(0,4).map(c=>({label:c.name,value:String(c.count)}))});
  if (r.favorite) pages.push({id:'favorite',kicker:annual?'THE ONE TO REMEMBER':'YOUR STANDOUT TABLE',title:r.favorite.name,detail:r.favorite.cuisine || 'A place worth remembering.',number:r.favorite.score?.toFixed(1),suffix:r.favorite.score!=null?'/ 10':undefined,visual:'podium',rows:[{label:'Places you’d return to',value:`${r.returnCount} of ${r.places}`} ]});
  if (r.meals || r.recipes) pages.push({id:'cooking',kicker:'MEANWHILE, IN YOUR KITCHEN',title:r.meals?'Home tasted\npretty good, too.':'A little inspiration.\nMade by you.',detail:r.cookingFavorite?`In your kitchen story: ${r.cookingFavorite}.`:'Your recipe collection is becoming something special.',number:String(r.meals||r.recipes),suffix:r.meals?'home meals logged':'recipes created',visual:'kitchen',rows:[{label:'Meals logged',value:String(r.meals)},{label:'Recipes created',value:String(r.recipes)}]});
  if (time!=='week' && r.cities.length) pages.push({id:'cities',kicker:'FOLLOW YOUR APPETITE',title:r.cities.length>1?'Good taste\ngets around.':'Your own corner\nof the food world.',detail:r.cities.slice(0,5).join(' · '),number:String(r.cities.length),suffix:r.cities.length===1?'city in your dining history':'cities in your dining history',visual:'orbit',rows:r.companions?[{label:'People tagged at your table',value:String(r.companions)}]:undefined});
  if (time!=='week') pages.push({id:'rhythm',kicker:annual?'TWELVE CHAPTERS, ONE YOU':'THE RHYTHM OF YOUR MONTH',title:'This is what\ngood taste looks like.',detail:'Logged visits, home meals, and recipes created throughout the '+time+'.',visual:'timeline'});
  if (r.taste.michelin?.recognized) pages.push({id:'michelin',kicker:'A LITTLE EXTRAORDINARY',title:'Some tables\nstay with you.',number:String(r.taste.michelin.recognized),suffix:'Guide-recognized favorites',detail:`${r.taste.michelin.recognized} of ${r.taste.michelin.loved} above-your-bar places match the current Michelin Guide dataset, including Stars, Bib Gourmand and Selected. Recognition may differ from the visit year.`,visual:'podium'});
  const b=r.community;
  const comparable=b?.average!=null && r.avgScore!=null;
  pages.push({id:'community',kicker:'YOU, IN GOOD COMPANY',title:comparable?Math.abs(r.avgScore!-b!.average!)<.1?'On the same\nwavelength.':r.avgScore!<b!.average!?'You set\na discerning bar.':'You found\na lot to love.':'A bigger table\nis taking shape.',detail:b?`Compared with ${b.users} ranked members. Community figures describe all-time published ratings, captured ${new Date(b.capturedAt).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}.`:'Community comparisons appear when at least 20 members have enough published history. Your own story is ready to enjoy.',visual:'community',rows:comparable?[{label:'Your '+time+' average',value:r.avgScore!.toFixed(1)},{label:'Community all-time average',value:b!.average!.toFixed(1)}]:b?.breadth!=null?[{label:'All-time cuisine breadth',value:`Broader than ${b.breadth}% of ranked peers`}]:undefined});
  if(annual) pages.push({id:'depth',kicker:'THE TASTE BEHIND THE TASTE',title:'Your palate,\nin finer detail.',detail:'Explore your personal rating baseline and the price tiers behind your positive ratings. This is a description of your history, not a measure of taste quality.',visual:'taste',pro:true,rows:[...(r.taste.priceConcentration!=null?[{label:'Price-range pattern',value:r.taste.priceConcentration>.5?'A focused comfort zone':'Room for variety'}]:[]),...(r.taste.anchor!=null?[{label:'Personal rating baseline',value:r.taste.anchor.toFixed(1)}]:[]),...(b?.grading!=null?[{label:'All-time grading style',value:`Tougher than ${b.grading}% of ranked peers`}]:[]),...(b?.distinctive!=null?[{label:'All-time premium + breadth index',value:`Above ${b.distinctive}% of ranked peers`}]:[])]});
  pages.push({id:'summary',kicker:'YOUR GOODEATS IN REVIEW',title:annual?'Here’s to\nthe next chapter.':'Good food.\nGood memories.\nVery you.',detail:'Your review is saved in Settings. Share a card with your favorite people.',visual:'summary',rows:[{label:'Places rated',value:String(r.places)},{label:'Cuisines',value:String(r.cuisines.length)},{label:'Home meals',value:String(r.meals)},{label:'Places saved',value:String(r.saved)}]});
  return pages;
}
