import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import MuxPlayer from '@mux/mux-player-react';
import {useAuth} from '../contexts/AuthContext';
import {supabase} from '../lib/supabase';
import {safetyError} from '../lib/community-safety';
import {PhotoImage} from '../components/PhotoImage';
import {fetchMuxTokens,type MuxPlaybackTokens} from '../lib/mux';
import '../components/Safety.css';
const LABELS:Record<string,string>={user_profiles:'Profile',posts:'Post',post_items:'Post media',reels:'Reel',community_ratings:'Restaurant review',community_photos:'Restaurant photo',home_meals:'Shared meal',lists:'List',wishlist:'Saved place',recipes:'Recipe',guides:'Guide',messages:'Message',post_comments:'Post comment',reel_comments:'Reel comment',activity_comments:'Review comment',recipe_reviews:'Recipe review',meal_reviews:'Meal review',recipe_comments:'Recipe comment',expert_recommendations:'Recommendation'};
interface Item {kind:string;content_id:string;user_id:string;snapshot:Record<string,unknown>;revision:string;status:string;id?:string;reason?:string;details?:string;}
function Media({item}:{item:Item}){
 const [tokens,setTokens]=useState<MuxPlaybackTokens|null>(null);const [media,setMedia]=useState('');
 const playback=typeof item.snapshot.mux_playback_id==='string'?item.snapshot.mux_playback_id:'';
 const path=String(item.snapshot.media_path||item.snapshot.video_path||'');const video=item.kind==='reels'||item.snapshot.media_type==='video';
 useEffect(()=>{let live=true;setTokens(null);setMedia('');if(playback)void fetchMuxTokens([{kind:item.kind==='reels'?'reel':'post_item',id:item.content_id}]).then(m=>{if(live)setTokens(m.get(item.content_id)||null);});
 if(path)void supabase.storage.from(item.kind==='reels'?'reels-videos':'post-media').createSignedUrl(path,300).then(({data})=>{if(live)setMedia(data?.signedUrl||'');});return()=>{live=false;};},[item.kind,item.content_id,item.revision,playback,path]);
 const images:string[]=[];const walk=(v:unknown,key='')=>{if(typeof v==='string'&&/^https:\/\//.test(v)&&(/\.(jpe?g|png|webp|avif|heic)(\?|$)/i.test(v)||v.includes('/storage/v1/')||/photo|image|avatar|cover|url/i.test(key)))images.push(v);else if(Array.isArray(v))v.forEach(x=>walk(x,key));else if(v&&typeof v==='object')Object.entries(v).forEach(([k,x])=>walk(x,k));};walk(item.snapshot);
 return <div className="safety-media">{playback?(tokens?<MuxPlayer playbackId={playback} tokens={{playback:tokens.playback,thumbnail:tokens.thumbnail,storyboard:tokens.storyboard}} streamType="on-demand"/>:<p>Video preview unavailable. Do not approve until you can review it.</p>):media?(video?<video src={media} controls playsInline/>:<PhotoImage src={media} alt="Uploaded content"/>):null}{[...new Set(images)].slice(0,40).map(src=><PhotoImage key={src} src={src} alt="Submitted photo"/>)}</div>;
}
export function ContentSafety({admin=false}:{admin?:boolean}){
 const {user,isAdmin,adminChecked}=useAuth();const [tab,setTab]=useState<'pending'|'reports'|'rejected'|'approved'>('pending');const [items,setItems]=useState<Item[]>([]);const [page,setPage]=useState(0);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [refresh,setRefresh]=useState(0);
 const allowed=!!user&&(!admin||isAdmin);
 useEffect(()=>{if(!allowed)return;let live=true;setLoading(true);setError('');let q=tab==='reports'?supabase.from('content_reports').select('*').eq('status','open').order('created_at'):supabase.from('content_moderation').select('*').eq('status',tab).order('updated_at');if(!admin)q=q.eq('user_id',user.id);void q.range(page*20,page*20+19).then(({data,error})=>{if(!live)return;if(error)setError(safetyError(error));else setItems((data||[]) as Item[]);setLoading(false);});return()=>{live=false;};},[allowed,admin,user?.id,tab,page,refresh]);
 const act=async(item:Item,action:string)=>{setBusy(true);setError('');try{const {error}=tab==='reports'?await supabase.rpc('resolve_content_report',{p_report:item.id,p_action:action}):await supabase.rpc('review_content',{p_kind:item.kind,p_id:item.content_id,p_revision:item.revision,p_approve:action==='approve'});if(error)throw error;setRefresh(x=>x+1);}catch(e){setError(safetyError(e));}finally{setBusy(false);}};
 if(admin&&adminChecked==='unknown')return <main className="safety-inbox" aria-busy="true">Checking access…</main>;
 if(!allowed)return <main className="safety-inbox">Page unavailable.</main>;
 return <main className="safety-inbox" data-analytics-private><Link to={admin?'/settings/support':'/settings/privacy'}>← Back to settings</Link><h1>{admin?'Community moderation':'Your publications'}</h1><p>{admin?'Review all text, photos and videos before approving. Reject harassment, hate, sexual content, threats, spam and personal information shared without permission. Respond promptly to reports.':'Pending publications are visible only to you and the moderation team. Your personal saves are not affected. Contact support if you need to appeal a decision.'}</p><nav>{(['pending',...(admin?['reports'] as const:[]),'rejected','approved'] as const).map(t=><button key={t} aria-pressed={tab===t} onClick={()=>{setTab(t);setPage(0);}}>{t==='reports'?'Reports':t.charAt(0).toUpperCase()+t.slice(1)}</button>)}<button onClick={()=>setRefresh(x=>x+1)}>Refresh</button></nav>{error&&<p role="alert" className="safety-error">{error}</p>}
 {loading?<div className="safety-skeleton" aria-label="Loading publications"/>:items.length?items.map(item=><article key={item.id||item.kind+item.content_id}><h2>{LABELS[item.kind]||'Shared content'}</h2>{item.reason&&<p><strong>Report: {item.reason}</strong><br/>{item.details}</p>}<Media item={item}/><dl>{Object.entries(item.snapshot).filter(([k,v])=>!['mux_playback_id','mux_status','media_path','video_path','photo_url','url','photo','cover_photo','avatar_url'].includes(k)&&v!==null&&v!=='').map(([key,value])=><React.Fragment key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{typeof value==='string'?value:JSON.stringify(value,null,2)}</dd></React.Fragment>)}</dl>{admin&&<div className="safety-actions">{tab==='reports'?<><button disabled={busy} onClick={()=>void act(item,'dismiss')}>Dismiss report</button><button disabled={busy} onClick={()=>void act(item,'remove')}>Remove content</button><button disabled={busy} onClick={()=>void act(item,'suspend')}>Suspend author</button></>:<><button disabled={busy} onClick={()=>void act(item,'reject')}>Reject</button><button disabled={busy} onClick={()=>void act(item,'approve')}>Approve</button></>}</div>}</article>):<p>No {tab==='reports'?'open reports':tab+' publications'}.</p>}
 <div className="safety-actions"><button disabled={loading||page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><button disabled={loading||items.length<20} onClick={()=>setPage(p=>p+1)}>Next</button></div><p><a href="mailto:gourmetcanvassupport@gmail.com">Contact support</a></p></main>;
}
