/**
 * Self-hosts the app's Google Fonts so the iOS bundle has no runtime
 * dependency on fonts.googleapis.com (offline first paint keeps the app's
 * typography; no FOUT on flaky networks).
 *
 * Downloads the latin + latin-ext woff2 subsets for every family the app
 * uses into public/fonts/ and writes public/fonts/fonts.css with the same
 * @font-face blocks pointed at the local files. index.html links that
 * stylesheet instead of the Google CDN.
 *
 * Re-run with `node scripts/fetch-fonts.mjs` if the family list in
 * CSS_URL changes.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Archivo:wght@400..800&family=Fraunces:ital,opsz,wght@0,9..144,200..900;1,9..144,200..900&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&family=Manrope:wght@200..800&family=Newsreader:ital,opsz,wght@0,6..72,200..800;1,6..72,200..800&family=Noto+Serif:ital,wght@0,100..900;1,100..900&family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,500;0,8..60,600;0,8..60,700;1,8..60,400;1,8..60,500&display=swap';

// A modern browser UA makes Google return variable-font woff2 subsets.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);
const OUT_DIR = path.resolve('public/fonts');

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

// The sheet is a sequence of "/* subset */\n@font-face { ... }" pairs.
const blockRe = /\/\* ([a-z-]+) \*\/\s*(@font-face\s*\{[^}]+\})/g;
const counters = new Map();
const downloads = [];
const outBlocks = [];

for (const [, subset, block] of css.matchAll(blockRe)) {
  if (!KEEP_SUBSETS.has(subset)) continue;
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1] ?? 'font';
  const style = block.match(/font-style:\s*(\w+)/)?.[1] ?? 'normal';
  const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  if (!url) continue;

  const slug = family.toLowerCase().replace(/\s+/g, '-');
  const key = `${slug}-${style}-${subset}`;
  const n = (counters.get(key) ?? 0) + 1;
  counters.set(key, n);
  const filename = n === 1 ? `${key}.woff2` : `${key}-${n}.woff2`;

  downloads.push({ url, filename });
  outBlocks.push(`/* ${subset} */\n${block.replace(url, `./${filename}`)}`);
}

await mkdir(OUT_DIR, { recursive: true });
let bytes = 0;
for (const { url, filename } of downloads) {
  const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  bytes += buf.length;
  await writeFile(path.join(OUT_DIR, filename), buf);
}

const header = `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n\n`;
await writeFile(path.join(OUT_DIR, 'fonts.css'), header + outBlocks.join('\n') + '\n');

console.log(`Wrote ${downloads.length} woff2 files (${(bytes / 1024).toFixed(0)} KB) + fonts.css to public/fonts/`);
